NIFTY50 = [
    "RELIANCE", "TCS", "HDFCBANK", "INFY", "ICICIBANK",
    "HINDUNILVR", "ITC", "SBIN", "BHARTIARTL", "KOTAKBANK",
    "LT", "AXISBANK", "ASIANPAINT", "MARUTI", "TITAN",
    "SUNPHARMA", "ULTRACEMCO", "BAJFINANCE", "WIPRO", "NESTLEIND",
    "POWERGRID", "NTPC", "TECHM", "HCLTECH", "ONGC",
    "TATAMOTORS", "BAJAJFINSV", "JSWSTEEL", "TATASTEEL", "ADANIENT",
    "ADANIPORTS", "COALINDIA", "DIVISLAB", "DRREDDY", "EICHERMOT",
    "GRASIM", "HEROMOTOCO", "HINDALCO", "INDUSINDBK", "CIPLA",
    "BRITANNIA", "APOLLOHOSP", "BPCL", "TATACONSUM", "SBILIFE",
    "HDFCLIFE", "BAJAJ-AUTO", "UPL", "VEDL", "M&M"
]

NIFTY_NEXT50 = [
    "ADANIGREEN", "ADANITRANS", "AMBUJACEM", "AUROPHARMA", "BANDHANBNK",
    "BERGEPAINT", "BIOCON", "BOSCHLTD", "CANBK", "CHOLAFIN",
    "COLPAL", "CONCOR", "CUMMINSIND", "DLF", "GODREJCP",
    "GODREJPROP", "HAVELLS", "ICICIGI", "ICICIPRULI", "INDIGO",
    "INDUSTOWER", "LUPIN", "MARICO", "MCDOWELL-N", "MUTHOOTFIN",
    "NAUKRI", "NMDC", "OFSS", "PAGEIND", "PIDILITIND",
    "PIIND", "PNB", "RECLTD", "SAIL", "SHREECEM",
    "SIEMENS", "SRF", "TORNTPHARM", "TRENT", "TRIDENT",
    "UBL", "UNIONBANK", "UNITDSPR", "VOLTAS", "WHIRLPOOL",
    "ZYDUSLIFE", "FEDERALBNK", "GMRINFRA", "HINDPETRO", "IOC"
]

MIDCAP_TOP100 = [
    "ABCAPITAL", "ABFRL", "AJANTPHARM", "ALKEM", "APLLTD",
    "ASTRAL", "ATUL", "AUBANK", "BALKRISIND", "BATAINDIA",
    "BHARATFORG", "BHEL", "CANFINHOME", "CASTROLIND", "CGPOWER",
    "CHAMBLFERT", "CROMPTON", "CESC", "DALBHARAT", "DEEPAKNTR",
    "DELTACORP", "EDELWEISS", "ESCORTS", "EXIDEIND", "FIIL",
    "FLUOROCHEM", "FORTIS", "GAIL", "GLAXO", "GLENMARK",
    "GNFC", "GPPL", "GSPL", "HONAUT", "IDFCFIRSTB",
    "IEX", "INDHOTEL", "INDIANB", "INDIACEM", "INOXWIND",
    "JKCEMENT", "JUBLFOOD", "JUBLPHARMA", "KANSAINER", "KAJARIACER",
    "LALPATHLAB", "LAURUSLABS", "LICHSGFIN", "LINDEINDIA", "LTTS",
    "MAHINDCIE", "MANAPPURAM", "MASFIN", "METROPOLIS", "MFSL",
    "MMFINANCE", "MOTHERSON", "MRF", "MTAR", "NATCOPHARM",
    "NAVINFLUOR", "NBCC", "NCC", "NLCINDIA", "OBEROIRLTY",
    "OFSS", "PERSISTENT", "PETRONET", "PFIZER", "PHOENIXLTD",
    "POLYCAB", "PRESTIGE", "PRINCEPIPE", "PVRINOX", "RAJESHEXPO",
    "RAMCOCEM", "RATNAMANI", "RKFORGE", "ROUTE", "SANOFI",
    "SCHAEFFLER", "SHYAMMETL", "SIGNATURE", "SKFINDIA", "SOBHA",
    "SOLARINDS", "STAR", "STARCEMENT", "SUMICHEM", "SUPREMEIND",
    "SYNGENE", "TANLA", "THYROCARE", "TIMKEN", "TRITURBINE",
    "TTKPRESTIG", "VGUARD", "VMART", "VSTIND", "ZENSARTECH"
]

SMALLCAP_TOP100 = [
    "AARTIIND", "ABBOTINDIA", "ACCELYA", "ACRYSIL", "AHLUCONT",
    "AIAENG", "AJAXENG", "AKZOINDIA", "ALEMBICLTD", "ALEXAFORBS",
    "AMARAJABAT", "AMBIKCO", "AMRUTANJAN", "ANANTRAJ", "ANDHRABANK",
    "ANDHRSUGAR", "ANGELONE", "ANURAS", "APARINDS", "APLAPOLLO",
    "ARVINDFASN", "ASAHIINDIA", "ASHIANA", "ASHOKA", "ASIANENE",
    "ASTERDM", "ASTRAZEN", "ATGL", "AVANTIFEED", "AXISCADES",
    "BAJAJHIND", "BAJAJHLDNG", "BALMLAWRIE", "BANARISUG", "BECTORFOOD",
    "BEML", "BFUTILITIE", "BIGBLOC", "BLISSGVS", "BORORENEW",
    "BSLIMITED", "BURGERKING", "CAMPUS", "CARBORUNIV", "CARERATING",
    "CCL", "CEATLTD", "CENTURYPLY", "CERA", "CHEMFAB",
    "CHEMPLASTS", "CLNINDIA", "COFFEDAY", "CONTROL", "COROMANDEL",
    "CRISIL", "CROWN", "DATAMATICS", "DBCORP", "DCMSHRIRAM",
    "DEEPAKFERT", "DEVYANI", "DHAMPUR", "DIAMONDYD", "DLINKINDIA",
    "DPABHUSHAN", "DREDGECORP", "ECLERX", "EIDPARRY", "ELECTCAST",
    "EMAMILTD", "EPIGRAL", "ESABINDIA", "ESSELPACK", "FINEORG",
    "FINPIPE", "FLOREAT", "FMGOETZE", "FORCEMOT", "GALAXYSURF",
    "GARFIBRES", "GESHIP", "GILLETTE", "GLOBALVECT", "GODREJAGRO",
    "GOODYEAR", "GREENPANEL", "GRINDWELL", "GULFOILLUB", "GUJALKALI",
    "GUJGASLTD", "HAPPSTMNDS", "HARDWYN", "HERITGFOOD", "HIMATSEIDE"
]
